# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c1e2ea00f48cfb53504792907abb57a6e86f04cff984f7e67fabadadd0a148ea8e4ea313a86695d341702303ab556c7ac246c7b5925c344dfd08ec06b07047c

test:
  secret_key_base: 22a3f00316e5b8f0c4708897e88835b38c507ad9ad9a940bd1c30b2ea3a8b2e1649750a113170ea949ac454256411ce3726f9c812c1de3b999dc48d5280daba9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
