# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ce6b21371de386ea1dea1665881eb4fb3ac2385aae5dd2682f286456104539b57330ccb87f5f60110fc2e2a9dd3bbca8f3f127eef9664288173c376ddc80d99

test:
  secret_key_base: 3b52c5fa961b0b527f1437fe4a6569d081b3e715f29bd4c56c6899162a8398810884c227553d6deae8e04ba7c20032bbd1dc6c1fc30944e24d55ee4857ce97a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
